## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
os:
  - linux
julia:
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999
before_script:
  - touch src/diff-zoo.jl # so that we can use the standard script
jobs:
  allow_failures:
  - julia: nightly
